### ISSUE TITLE
Prepare is not creating dataset.yaml correctly for cooking

### ISSUE THREAD

**Issue by voegtlel** [NVIDIA/Megatron-Energon#54]
Apparently, it creates
```yaml
sample_type:
  __module__: megatron.energon
  __class__: CrudeSampleDummy
```
but should read
```yaml
__module__: megatron.energon
__class__: CrudeWebdataset
```
